name: fcm_shared_isolate
description: Firebase Messaging Plugin for Flutter supporting shared isolate
version: 0.0.1
repository: https://gitlab.com/famedly/libraries/fcm_shared_isolate

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  firebase_core: ^0.5.3
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.11.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.famedly.fcm_shared_isolate
        pluginClass: FcmSharedIsolatePlugin
      ios:
        pluginClass: FcmSharedIsolatePlugin
